version: "3.9"
services:
  relay:
    image: rezarajan/freebird
    volumes:
      - sockets:/opt/cardano/cnode/sockets
      - db:/opt/cardano/cnode/db
    environment:
      - NETWORK=testnet
    networks:
      - relay
    ports:
      - 6000:6000
    container_name: relay-testnet

volumes:
  sockets:
    name: sockets-testnet
  db:
    name: db-testnet

networks:
  relay:
    name: relay-testnet
