version: "3.9"
services:
  proxy:
    build: ./
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 3001:3001
    networks:
      - relay1
      - relay2
    container_name: proxy

networks:
  relay1:
    external: true
  relay2:
    external: true