version: "3.9"
services:
  relay:
    image: cardanocommunity/cardano-node
    volumes:
      - sockets:/opt/cardano/cnode/sockets
      - configs:/opt/cardano/cnode/priv
      - db:/opt/cardano/cnode/db
    environment:
      - NETWORK=mainnet
    ports:
      - 9000:6000
    security_opt:
      - no-new-privileges
    container_name: relay1
    networks:
      - relay1

volumes:
  sockets:
    external: true
  configs:
    external: true
  db:
    external: true

networks:
  relay1:
    external: true